model:
  NAME: GMMBaseSeg
  encoder_args:
    NAME: PointNextEncoder
    blocks: [1, 3, 5, 3, 3]
    strides: [1, 4, 4, 4, 4]
    sa_layers: 1 
    sa_use_res: False 
    width: 32
    in_channels: 4
    expansion: 4
    radius: 0.1
    nsample: 32
    aggr_args:
      feature_type: 'dp_fj'
      reduction: 'max'
    group_args:
      NAME: 'ballquery'
      normalize_dp: True
    conv_args:
      order: conv-norm-act
    act_args:
      act: 'relu'
    norm_args:
      norm: 'bn'
  decoder_args:
    NAME: GMMPointNextDecoder
  cls_args:
    NAME: PointNextGMMSeg
    num_classes: 13

decoder_params:
    embed_dim: 64
    num_components: 5
    factor_n: 1
    factor_c: 1
    factor_p: 1,
    mem_size: 36000
    max_sample_size: 40
    update_GMM_interval: 5
    update_loop: 5

preTrain:
  is_pretrain: True


preLoadGMMConfig:
  is_load_gmm: True
  pretrain_path: /

dataset:
  train:
    loop: 30

pretrained_path: 

batch_size: 8

