model:
  NAME: GMMBaseSeg
  encoder_args:
    NAME: PointNet2Encoder
    in_channels: 4
    strides: [4, 4, 4, 4]
    blocks: [3, 3, 3, 3]
    width_scaling: 3
    double_last_channel: False
    layers: 3
    use_res: True 
    query_as_support: True
    mlps: [[[16, 16, 32], [32, 32, 64]],
           [[64, 64, 128], [64, 96, 128]],
           [[128, 196, 256], [128, 196, 256]],
           [[256, 256, 512], [256, 384, 512]]]
    stem_conv: True
    stem_aggr: True
    radius: [[0.1, 0.2], [0.2, 0.4], [0.4, 0.8], [0.8, 1.6]]
    num_samples: [[16, 32], [16, 32], [16, 32], [16, 32]]
    sampler: fps
    aggr_args:
      NAME: 'ASSA'
      feature_type: 'assa'
      anisotropic: True 
      reduction: 'mean'
    group_args:
      NAME: 'ballquery'
      use_xyz: True
      normalize_dp: True
    conv_args:
      order: conv-norm-act
    act_args:
      act: 'relu'
    norm_args:
      norm: 'bn'
  decoder_args:
    NAME: GMMPointNet2Decoder
    fp_mlps: [[64, 64], [128, 128], [256, 256], [512, 512]]
  cls_args:
    NAME: ASSANetGMMSeg
    num_classes: 13


# ---------------------------------------------------------------------------- #
# Data Augmentation 
# ---------------------------------------------------------------------------- #
datatransforms:
  train: [ChromaticAutoContrast, PointsToTensor, PointCloudScaling, PointCloudCenterAndNormalize, PointCloudRotation, PointCloudJitter, ChromaticDropGPU, ChromaticNormalize]
  val: [PointsToTensor, PointCloudCenterAndNormalize, ChromaticNormalize]
  vote: [ChromaticDropGPU]
  kwargs:
    color_drop: 0.2
    gravity_dim: 2
    scale: [0.9, 1.1]
    angle: [0, 0, 1]
    jitter_sigma: 0.005
    jitter_clip: 0.02
    normalize: False 


dataset:
  train:
    data_rate: "null"


criterion_args:
  NAME: SmoothCrossEntropy
  label_smoothing: 0.2

decoder_params:
    embed_dim: 64
    num_components: 5
    factor_n: 1
    factor_c: 1
    factor_p: 1,
    mem_size: 36000
    max_sample_size: 40
    update_GMM_interval: 5
    update_loop: 5

optimizer:
 NAME: 'adamw'  
 weight_decay: 1.0e-4

sched: cosine
warmup_epochs: 0

lr: 0.01 
min_lr: 1.0e-5 #

epochs: 150
pretrained_path:

batch_size: 32
